In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('2025 Teams.csv')
df

                      Team  code                 team_and_mascot
0               Ohio State   194             Ohio State Buckeyes
1                      LSU    99                      LSU Tigers
2                    Miami  2390                Miami Hurricanes
3            Florida State    52         Florida State Seminoles
4                   Auburn     2                   Auburn Tigers
5               Iowa State    66             Iowa State Cyclones
6             Georgia Tech    59     Georgia Tech Yellow Jackets
7           South Carolina  2579        South Carolina Gamecocks
8                 Nebraska   158            Nebraska Cornhuskers
9                Tennessee  2633            Tennessee Volunteers
10                    Utah   254                       Utah Utes
11           South Florida    58             South Florida Bulls
12                     TCU  2628                TCU Horned Frogs
13               Texas A&M   245                Texas A&M Aggies
14                    Rice   242                       Rice Owls
15                 Rutgers   164         Rutgers Scarlet Knights
16              Louisville    97            Louisville Cardinals
17        Central Michigan  2117      Central Michigan Chippewas
18                NC State   154               NC State Wolfpack
19              California    25         California Golden Bears
20                  Kansas  2305                 Kansas Jayhawks
21                  Tulane  2655               Tulane Green Wave
22                Maryland   120              Maryland Terrapins
23                Kentucky    96               Kentucky Wildcats
24                 Indiana    84                Indiana Hoosiers
25               Wisconsin   275               Wisconsin Badgers
26       Mississippi State   344      Mississippi State Bulldogs
27                     UCF  2116                     UCF Knights
28                  Oregon  2483                    Oregon Ducks
29              Washington   264              Washington Huskies
30                    UNLV  2439                     UNLV Rebels
31                 Georgia    61                Georgia Bulldogs
32                 Wyoming  2751                 Wyoming Cowboys
33               Minnesota   135        Minnesota Golden Gophers
34                Michigan   130             Michigan Wolverines
35          Michigan State   127         Michigan State Spartans
36                Ole Miss   145                 Ole Miss Rebels
37        Washington State   265        Washington State Cougars
38        Western Kentucky    98    Western Kentucky Hilltoppers
39               App State  2026          App State Mountaineers
40             Wake Forest   154       Wake Forest Demon Deacons
41                Virginia   258              Virginia Cavaliers
42                 Houston   248                 Houston Cougars
43             Texas State   326             Texas State Bobcats
44              Penn State   213        Penn State Nittany Lions
45                 Hawai'i    62        Hawai'i Rainbow Warriors
46                  Temple   218                     Temple Owls
47              Utah State   328               Utah State Aggies
48          Oklahoma State   197          Oklahoma State Cowboys
49                 Arizona    12                Arizona Wildcats
50            Fresno State   278           Fresno State Bulldogs
51           Arizona State     9        Arizona State Sun Devils
52                  Purdue  2509             Purdue Boilermakers
53                 Memphis   235                  Memphis Tigers
54                   Tulsa   202          Tulsa Golden Hurricane
55                Oklahoma   201                Oklahoma Sooners
56          Arkansas State  2032       Arkansas State Red Wolves
57                     USC    30                     USC Trojans
58                Missouri   142                 Missouri Tigers
59                    Duke   150                Duke Blue Devils
60          Louisiana Tech  2348         Louisiana Tech Bulldogs
61                    Troy  2653                    Troy Trojans
62                     SMU  2567                    SMU Mustangs
63                 Liberty  2335                  Liberty Flames
64            Kansas State  2306           Kansas State Wildcats
65                    Iowa  2294                   Iowa Hawkeyes
66           Bowling Green   189           Bowling Green Falcons
67              Pittsburgh   221             Pittsburgh Panthers
68              Kent State  2309       Kent State Golden Flashes
69         San Diego State    21          San Diego State Aztecs
70          Boston College   103           Boston College Eagles
71                Illinois   356        Illinois Fighting Illini
72                     UAB     5                     UAB Blazers
73              Vanderbilt   238           Vanderbilt Commodores
74             Boise State    68             Boise State Broncos
75           South Alabama     6           South Alabama Jaguars
76                     BYU   252                     BYU Cougars
77           James Madison   256             James Madison Dukes
78             North Texas   249          North Texas Mean Green
79           West Virginia   277      West Virginia Mountaineers
80       Northern Illinois  2459       Northern Illinois Huskies
81               UL Monroe  2433              UL Monroe Warhawks
82                 Florida    57                  Florida Gators
83                   Uconn    41                   UConn Huskies
84                Arkansas     8             Arkansas Razorbacks
85                    Navy  2426                 Navy Midshipmen
86               Air Force  2005               Air Force Falcons
87        New Mexico State   166         New Mexico State Aggies
88   Florida International  2229  Florida International Panthers
89            Northwestern    77           Northwestern Wildcats
90                Delaware    48              Delaware Blue Hens
91              Texas Tech  2641          Texas Tech Red Raiders
92          San Jose State    23         San José State Spartans
93                Stanford    24               Stanford Cardinal
94                    UCLA    26                     UCLA Bruins
95          Colorado State    36             Colorado State Rams
96                Colorado    38              Colorado Buffaloes
97      Jacksonville State    55    Jacksonville State Gamecocks
98              Notre Dame    87       Notre Dame Fighting Irish
99           Massachusetts   113         Massachusetts Minutemen
100          East Carolina   151           East Carolina Pirates
101         North Carolina   153        North Carolina Tar Heels
102             New Mexico   167                New Mexico Lobos
103               Syracuse   183                 Syracuse Orange
104             Miami (OH)   193             Miami (OH) RedHawks
105                   Ohio   195                    Ohio Bobcats
106           Oregon State   204            Oregon State Beavers
107                Clemson   228                  Clemson Tigers
108                 Baylor   239                    Baylor Bears
109                  Texas   251                 Texas Longhorns
110          Virginia Tech   259            Virginia Tech Hokies
111               Marshall   276        Marshall Thundering Herd
112       Georgia Southern   290         Georgia Southern Eagles
113           Old Dominion   295           Old Dominion Monarchs
114              Louisiana   309         Louisiana Ragin' Cajuns
115       Coastal Carolina   324   Coastal Carolina Chanticleers
116                Alabama   333            Alabama Crimson Tide
117         Kennesaw State   338             Kennesaw State Owls
118                   Army   349              Army Black Knights
119                  Akron  2006                      Akron Zips
120             Ball State  2050            Ball State Cardinals
121                Buffalo  2084                   Buffalo Bulls
122             Cincinnati  2132             Cincinnati Bearcats
123       Eastern Michigan  2199         Eastern Michigan Eagles
124       Florida Atlantic  2226           Florida Atlantic Owls
125          Georgia State  2247          Georgia State Panthers
126       Middle Tennessee  2393   Middle Tennessee Blue Raiders
127              Charlotte  2429                 Charlotte 49ers
128                 Nevada  2440                Nevada Wolf Pack
129            Sam Houston  2534            Sam Houston Bearkats
130          Southern Miss  2572     Southern Miss Golden Eagles
131         Missouri State  2623            Missouri State Bears
132                   UTSA  2636                UTSA Roadrunners
133                   UTEP  2638                     UTEP Miners
134                 Toledo  2649                  Toledo Rockets
135       Western Michigan  2711        Western Michigan Broncos

In [3]:
df['Team'].isna().sum()

np.int64(0)

In [4]:
df['Team'].value_counts()

Team
Ohio State               1
LSU                      1
Miami                    1
Florida State            1
Auburn                   1
Iowa State               1
Georgia Tech             1
South Carolina           1
Nebraska                 1
Tennessee                1
Utah                     1
South Florida            1
TCU                      1
Texas A&M                1
Rice                     1
Rutgers                  1
Louisville               1
Central Michigan         1
NC State                 1
California               1
Kansas                   1
Tulane                   1
Maryland                 1
Kentucky                 1
Indiana                  1
Wisconsin                1
Mississippi State        1
UCF                      1
Oregon                   1
Washington               1
UNLV                     1
Georgia                  1
Wyoming                  1
Minnesota                1
Michigan                 1
Michigan State           1
Ole Miss                 1
Washington State         1
Western Kentucky         1
App State                1
Wake Forest              1
Virginia                 1
Houston                  1
Texas State              1
Penn State               1
Hawai'i                  1
Temple                   1
Utah State               1
Oklahoma State           1
Arizona                  1
Fresno State             1
Arizona State            1
Purdue                   1
Memphis                  1
Tulsa                    1
Oklahoma                 1
Arkansas State           1
USC                      1
Missouri                 1
Duke                     1
Louisiana Tech           1
Troy                     1
SMU                      1
Liberty                  1
Kansas State             1
Iowa                     1
Bowling Green            1
Pittsburgh               1
Kent State               1
San Diego State          1
Boston College           1
Illinois                 1
UAB                      1
Vanderbilt               1
Boise State              1
South Alabama            1
BYU                      1
James Madison            1
North Texas              1
West Virginia            1
Northern Illinois        1
UL Monroe                1
Florida                  1
Uconn                    1
Arkansas                 1
Navy                     1
Air Force                1
New Mexico State         1
Florida International    1
Northwestern             1
Delaware                 1
Texas Tech               1
San Jose State           1
Stanford                 1
UCLA                     1
Colorado State           1
Colorado                 1
Jacksonville State       1
Notre Dame               1
Massachusetts            1
East Carolina            1
North Carolina           1
New Mexico               1
Syracuse                 1
Miami (OH)               1
Ohio                     1
Oregon State             1
Clemson                  1
Baylor                   1
Texas                    1
Virginia Tech            1
Marshall                 1
Georgia Southern         1
Old Dominion             1
Louisiana                1
Coastal Carolina         1
Alabama                  1
Kennesaw State           1
Army                     1
Akron                    1
Ball State               1
Buffalo                  1
Cincinnati               1
Eastern Michigan         1
Florida Atlantic         1
Georgia State            1
Middle Tennessee         1
Charlotte                1
Nevada                   1
Sam Houston              1
Southern Miss            1
Missouri State           1
UTSA                     1
UTEP                     1
Toledo                   1
Western Michigan         1
Name: count, dtype: int64

In [5]:
unique_team = df['Team'].unique()
unique_team = sorted(unique_team)
unique_team

['Air Force',
 'Akron',
 'Alabama',
 'App State',
 'Arizona',
 'Arizona State',
 'Arkansas',
 'Arkansas State',
 'Army',
 'Auburn',
 'BYU',
 'Ball State',
 'Baylor',
 'Boise State',
 'Boston College',
 'Bowling Green',
 'Buffalo',
 'California',
 'Central Michigan',
 'Charlotte',
 'Cincinnati',
 'Clemson',
 'Coastal Carolina',
 'Colorado',
 'Colorado State',
 'Delaware',
 'Duke',
 'East Carolina',
 'Eastern Michigan',
 'Florida',
 'Florida Atlantic',
 'Florida International',
 'Florida State',
 'Fresno State',
 'Georgia',
 'Georgia Southern',
 'Georgia State',
 'Georgia Tech',
 "Hawai'i",
 'Houston',
 'Illinois',
 'Indiana',
 'Iowa',
 'Iowa State',
 'Jacksonville State',
 'James Madison',
 'Kansas',
 'Kansas State',
 'Kennesaw State',
 'Kent State',
 'Kentucky',
 'LSU',
 'Liberty',
 'Louisiana',
 'Louisiana Tech',
 'Louisville',
 'Marshall',
 'Maryland',
 'Massachusetts',
 'Memphis',
 'Miami',
 'Miami (OH)',
 'Michigan',
 'Michigan State',
 'Middle Tennessee',
 'Minnesota',
 'Mississippi State',
 'Missouri',
 'Missouri State',
 'NC State',
 'Navy',
 'Nebraska',
 'Nevada',
 'New Mexico',
 'New Mexico State',
 'North Carolina',
 'North Texas',
 'Northern Illinois',
 'Northwestern',
 'Notre Dame',
 'Ohio',
 'Ohio State',
 'Oklahoma',
 'Oklahoma State',
 'Old Dominion',
 'Ole Miss',
 'Oregon',
 'Oregon State',
 'Penn State',
 'Pittsburgh',
 'Purdue',
 'Rice',
 'Rutgers',
 'SMU',
 'Sam Houston',
 'San Diego State',
 'San Jose State',
 'South Alabama',
 'South Carolina',
 'South Florida',
 'Southern Miss',
 'Stanford',
 'Syracuse',
 'TCU',
 'Temple',
 'Tennessee',
 'Texas',
 'Texas A&M',
 'Texas State',
 'Texas Tech',
 'Toledo',
 'Troy',
 'Tulane',
 'Tulsa',
 'UAB',
 'UCF',
 'UCLA',
 'UL Monroe',
 'UNLV',
 'USC',
 'UTEP',
 'UTSA',
 'Uconn',
 'Utah',
 'Utah State',
 'Vanderbilt',
 'Virginia',
 'Virginia Tech',
 'Wake Forest',
 'Washington',
 'Washington State',
 'West Virginia',
 'Western Kentucky',
 'Western Michigan',
 'Wisconsin',
 'Wyoming']

In [6]:
df['Team'].value_counts().sort_index()

Team
Air Force                1
Akron                    1
Alabama                  1
App State                1
Arizona                  1
Arizona State            1
Arkansas                 1
Arkansas State           1
Army                     1
Auburn                   1
BYU                      1
Ball State               1
Baylor                   1
Boise State              1
Boston College           1
Bowling Green            1
Buffalo                  1
California               1
Central Michigan         1
Charlotte                1
Cincinnati               1
Clemson                  1
Coastal Carolina         1
Colorado                 1
Colorado State           1
Delaware                 1
Duke                     1
East Carolina            1
Eastern Michigan         1
Florida                  1
Florida Atlantic         1
Florida International    1
Florida State            1
Fresno State             1
Georgia                  1
Georgia Southern         1
Georgia State            1
Georgia Tech             1
Hawai'i                  1
Houston                  1
Illinois                 1
Indiana                  1
Iowa                     1
Iowa State               1
Jacksonville State       1
James Madison            1
Kansas                   1
Kansas State             1
Kennesaw State           1
Kent State               1
Kentucky                 1
LSU                      1
Liberty                  1
Louisiana                1
Louisiana Tech           1
Louisville               1
Marshall                 1
Maryland                 1
Massachusetts            1
Memphis                  1
Miami                    1
Miami (OH)               1
Michigan                 1
Michigan State           1
Middle Tennessee         1
Minnesota                1
Mississippi State        1
Missouri                 1
Missouri State           1
NC State                 1
Navy                     1
Nebraska                 1
Nevada                   1
New Mexico               1
New Mexico State         1
North Carolina           1
North Texas              1
Northern Illinois        1
Northwestern             1
Notre Dame               1
Ohio                     1
Ohio State               1
Oklahoma                 1
Oklahoma State           1
Old Dominion             1
Ole Miss                 1
Oregon                   1
Oregon State             1
Penn State               1
Pittsburgh               1
Purdue                   1
Rice                     1
Rutgers                  1
SMU                      1
Sam Houston              1
San Diego State          1
San Jose State           1
South Alabama            1
South Carolina           1
South Florida            1
Southern Miss            1
Stanford                 1
Syracuse                 1
TCU                      1
Temple                   1
Tennessee                1
Texas                    1
Texas A&M                1
Texas State              1
Texas Tech               1
Toledo                   1
Troy                     1
Tulane                   1
Tulsa                    1
UAB                      1
UCF                      1
UCLA                     1
UL Monroe                1
UNLV                     1
USC                      1
UTEP                     1
UTSA                     1
Uconn                    1
Utah                     1
Utah State               1
Vanderbilt               1
Virginia                 1
Virginia Tech            1
Wake Forest              1
Washington               1
Washington State         1
West Virginia            1
Western Kentucky         1
Western Michigan         1
Wisconsin                1
Wyoming                  1
Name: count, dtype: int64

In [7]:
df['code'].isna().sum()

np.int64(0)

In [8]:
df['code'].value_counts().sort_index()

code
2       1
5       1
6       1
8       1
9       1
12      1
21      1
23      1
24      1
25      1
26      1
30      1
36      1
38      1
41      1
48      1
52      1
55      1
57      1
58      1
59      1
61      1
62      1
66      1
68      1
77      1
84      1
87      1
96      1
97      1
98      1
99      1
103     1
113     1
120     1
127     1
130     1
135     1
142     1
145     1
150     1
151     1
153     1
154     2
158     1
164     1
166     1
167     1
183     1
189     1
193     1
194     1
195     1
197     1
201     1
202     1
204     1
213     1
218     1
221     1
228     1
235     1
238     1
239     1
242     1
245     1
248     1
249     1
251     1
252     1
254     1
256     1
258     1
259     1
264     1
265     1
275     1
276     1
277     1
278     1
290     1
295     1
309     1
324     1
326     1
328     1
333     1
338     1
344     1
349     1
356     1
2005    1
2006    1
2026    1
2032    1
2050    1
2084    1
2116    1
2117    1
2132    1
2199    1
2226    1
2229    1
2247    1
2294    1
2305    1
2306    1
2309    1
2335    1
2348    1
2390    1
2393    1
2426    1
2429    1
2433    1
2439    1
2440    1
2459    1
2483    1
2509    1
2534    1
2567    1
2572    1
2579    1
2623    1
2628    1
2633    1
2636    1
2638    1
2641    1
2649    1
2653    1
2655    1
2711    1
2751    1
Name: count, dtype: int64

In [9]:
df['code'].unique()

array([ 194,   99, 2390,   52,    2,   66,   59, 2579,  158, 2633,  254,
         58, 2628,  245,  242,  164,   97, 2117,  154,   25, 2305, 2655,
        120,   96,   84,  275,  344, 2116, 2483,  264, 2439,   61, 2751,
        135,  130,  127,  145,  265,   98, 2026,  258,  248,  326,  213,
         62,  218,  328,  197,   12,  278,    9, 2509,  235,  202,  201,
       2032,   30,  142,  150, 2348, 2653, 2567, 2335, 2306, 2294,  189,
        221, 2309,   21,  103,  356,    5,  238,   68,    6,  252,  256,
        249,  277, 2459, 2433,   57,   41,    8, 2426, 2005,  166, 2229,
         77,   48, 2641,   23,   24,   26,   36,   38,   55,   87,  113,
        151,  153,  167,  183,  193,  195,  204,  228,  239,  251,  259,
        276,  290,  295,  309,  324,  333,  338,  349, 2006, 2050, 2084,
       2132, 2199, 2226, 2247, 2393, 2429, 2440, 2534, 2572, 2623, 2636,
       2638, 2649, 2711])

In [10]:
df['team_and_mascot'].isna().sum()

np.int64(0)

In [11]:
df['team_and_mascot'].value_counts().sort_index()

team_and_mascot
Air Force Falcons                 1
Akron Zips                        1
Alabama Crimson Tide              1
App State Mountaineers            1
Arizona State Sun Devils          1
Arizona Wildcats                  1
Arkansas Razorbacks               1
Arkansas State Red Wolves         1
Army Black Knights                1
Auburn Tigers                     1
BYU Cougars                       1
Ball State Cardinals              1
Baylor Bears                      1
Boise State Broncos               1
Boston College Eagles             1
Bowling Green Falcons             1
Buffalo Bulls                     1
California Golden Bears           1
Central Michigan Chippewas        1
Charlotte 49ers                   1
Cincinnati Bearcats               1
Clemson Tigers                    1
Coastal Carolina Chanticleers     1
Colorado Buffaloes                1
Colorado State Rams               1
Delaware Blue Hens                1
Duke Blue Devils                  1
East Carolina Pirates             1
Eastern Michigan Eagles           1
Florida Atlantic Owls             1
Florida Gators                    1
Florida International Panthers    1
Florida State Seminoles           1
Fresno State Bulldogs             1
Georgia Bulldogs                  1
Georgia Southern Eagles           1
Georgia State Panthers            1
Georgia Tech Yellow Jackets       1
Hawai'i Rainbow Warriors          1
Houston Cougars                   1
Illinois Fighting Illini          1
Indiana Hoosiers                  1
Iowa Hawkeyes                     1
Iowa State Cyclones               1
Jacksonville State Gamecocks      1
James Madison Dukes               1
Kansas Jayhawks                   1
Kansas State Wildcats             1
Kennesaw State Owls               1
Kent State Golden Flashes         1
Kentucky Wildcats                 1
LSU Tigers                        1
Liberty Flames                    1
Louisiana Ragin' Cajuns           1
Louisiana Tech Bulldogs           1
Louisville Cardinals              1
Marshall Thundering Herd          1
Maryland Terrapins                1
Massachusetts Minutemen           1
Memphis Tigers                    1
Miami (OH) RedHawks               1
Miami Hurricanes                  1
Michigan State Spartans           1
Michigan Wolverines               1
Middle Tennessee Blue Raiders     1
Minnesota Golden Gophers          1
Mississippi State Bulldogs        1
Missouri State Bears              1
Missouri Tigers                   1
NC State Wolfpack                 1
Navy Midshipmen                   1
Nebraska Cornhuskers              1
Nevada Wolf Pack                  1
New Mexico Lobos                  1
New Mexico State Aggies           1
North Carolina Tar Heels          1
North Texas Mean Green            1
Northern Illinois Huskies         1
Northwestern Wildcats             1
Notre Dame Fighting Irish         1
Ohio Bobcats                      1
Ohio State Buckeyes               1
Oklahoma Sooners                  1
Oklahoma State Cowboys            1
Old Dominion Monarchs             1
Ole Miss Rebels                   1
Oregon Ducks                      1
Oregon State Beavers              1
Penn State Nittany Lions          1
Pittsburgh Panthers               1
Purdue Boilermakers               1
Rice Owls                         1
Rutgers Scarlet Knights           1
SMU Mustangs                      1
Sam Houston Bearkats              1
San Diego State Aztecs            1
San José State Spartans           1
South Alabama Jaguars             1
South Carolina Gamecocks          1
South Florida Bulls               1
Southern Miss Golden Eagles       1
Stanford Cardinal                 1
Syracuse Orange                   1
TCU Horned Frogs                  1
Temple Owls                       1
Tennessee Volunteers              1
Texas A&M Aggies                  1
Texas Longhorns                   1
Texas State Bobcats               1
Texas Tech Red Raiders            1
Toledo Rockets                    1
Troy Trojans                      1
Tulane Green Wave                 1
Tulsa Golden Hurricane            1
UAB Blazers                       1
UCF Knights                       1
UCLA Bruins                       1
UConn Huskies                     1
UL Monroe Warhawks                1
UNLV Rebels                       1
USC Trojans                       1
UTEP Miners                       1
UTSA Roadrunners                  1
Utah State Aggies                 1
Utah Utes                         1
Vanderbilt Commodores             1
Virginia Cavaliers                1
Virginia Tech Hokies              1
Wake Forest Demon Deacons         1
Washington Huskies                1
Washington State Cougars          1
West Virginia Mountaineers        1
Western Kentucky Hilltoppers      1
Western Michigan Broncos          1
Wisconsin Badgers                 1
Wyoming Cowboys                   1
Name: count, dtype: int64

In [12]:
unique_team_and_mascot = df['team_and_mascot'].unique()
unique_team_and_mascot = sorted(unique_team_and_mascot)
unique_team_and_mascot

['Air Force Falcons',
 'Akron Zips',
 'Alabama Crimson Tide',
 'App State Mountaineers',
 'Arizona State Sun Devils',
 'Arizona Wildcats',
 'Arkansas Razorbacks',
 'Arkansas State Red Wolves',
 'Army Black Knights',
 'Auburn Tigers',
 'BYU Cougars',
 'Ball State Cardinals',
 'Baylor Bears',
 'Boise State Broncos',
 'Boston College Eagles',
 'Bowling Green Falcons',
 'Buffalo Bulls',
 'California Golden Bears',
 'Central Michigan Chippewas',
 'Charlotte 49ers',
 'Cincinnati Bearcats',
 'Clemson Tigers',
 'Coastal Carolina Chanticleers',
 'Colorado Buffaloes',
 'Colorado State Rams',
 'Delaware Blue Hens',
 'Duke Blue Devils',
 'East Carolina Pirates',
 'Eastern Michigan Eagles',
 'Florida Atlantic Owls',
 'Florida Gators',
 'Florida International Panthers',
 'Florida State Seminoles',
 'Fresno State Bulldogs',
 'Georgia Bulldogs',
 'Georgia Southern Eagles',
 'Georgia State Panthers',
 'Georgia Tech Yellow Jackets',
 "Hawai'i Rainbow Warriors",
 'Houston Cougars',
 'Illinois Fighting Illini',
 'Indiana Hoosiers',
 'Iowa Hawkeyes',
 'Iowa State Cyclones',
 'Jacksonville State Gamecocks',
 'James Madison Dukes',
 'Kansas Jayhawks',
 'Kansas State Wildcats',
 'Kennesaw State Owls',
 'Kent State Golden Flashes',
 'Kentucky Wildcats',
 'LSU Tigers',
 'Liberty Flames',
 "Louisiana Ragin' Cajuns",
 'Louisiana Tech Bulldogs',
 'Louisville Cardinals',
 'Marshall Thundering Herd',
 'Maryland Terrapins',
 'Massachusetts Minutemen',
 'Memphis Tigers',
 'Miami (OH) RedHawks',
 'Miami Hurricanes',
 'Michigan State Spartans',
 'Michigan Wolverines',
 'Middle Tennessee Blue Raiders',
 'Minnesota Golden Gophers',
 'Mississippi State Bulldogs',
 'Missouri State Bears',
 'Missouri Tigers',
 'NC State Wolfpack',
 'Navy Midshipmen',
 'Nebraska Cornhuskers',
 'Nevada Wolf Pack',
 'New Mexico Lobos',
 'New Mexico State Aggies',
 'North Carolina Tar Heels',
 'North Texas Mean Green',
 'Northern Illinois Huskies',
 'Northwestern Wildcats',
 'Notre Dame Fighting Irish',
 'Ohio Bobcats',
 'Ohio State Buckeyes',
 'Oklahoma Sooners',
 'Oklahoma State Cowboys',
 'Old Dominion Monarchs',
 'Ole Miss Rebels',
 'Oregon Ducks',
 'Oregon State Beavers',
 'Penn State Nittany Lions',
 'Pittsburgh Panthers',
 'Purdue Boilermakers',
 'Rice Owls',
 'Rutgers Scarlet Knights',
 'SMU Mustangs',
 'Sam Houston Bearkats',
 'San Diego State Aztecs',
 'San José State Spartans',
 'South Alabama Jaguars',
 'South Carolina Gamecocks',
 'South Florida Bulls',
 'Southern Miss Golden Eagles',
 'Stanford Cardinal',
 'Syracuse Orange',
 'TCU Horned Frogs',
 'Temple Owls',
 'Tennessee Volunteers',
 'Texas A&M Aggies',
 'Texas Longhorns',
 'Texas State Bobcats',
 'Texas Tech Red Raiders',
 'Toledo Rockets',
 'Troy Trojans',
 'Tulane Green Wave',
 'Tulsa Golden Hurricane',
 'UAB Blazers',
 'UCF Knights',
 'UCLA Bruins',
 'UConn Huskies',
 'UL Monroe Warhawks',
 'UNLV Rebels',
 'USC Trojans',
 'UTEP Miners',
 'UTSA Roadrunners',
 'Utah State Aggies',
 'Utah Utes',
 'Vanderbilt Commodores',
 'Virginia Cavaliers',
 'Virginia Tech Hokies',
 'Wake Forest Demon Deacons',
 'Washington Huskies',
 'Washington State Cougars',
 'West Virginia Mountaineers',
 'Western Kentucky Hilltoppers',
 'Western Michigan Broncos',
 'Wisconsin Badgers',
 'Wyoming Cowboys']