In [3]:
import streamlit as st
import pandas as pd
from datetime import datetime
import numpy as np

In [4]:
df = pd.read_csv('mergedTrainingData.csv')
df

,Unnamed: 0,week,season,Team,opponent,code,date,win_loss,OT,OT_num,...,home_game,CONF,SOR,FPI,SOS,GC,AVGWP,AP_rank,opponent_rank,rank_change
0,1,10,2021,Air Force,Army,2005,"Sat, Nov 6",L,True,,...,True,Mountain West,33,66,110,24,6,NaN,NaN,0.0
1,2,10,2021,Akron,Western Michigan,2006,"Tue, Nov 9",L,False,NaN,...,False,MAC,127,128,67,118,125,NaN,NaN,0.0
2,3,10,2021,Alabama,LSU,333,"Sat, Nov 6",W,False,NaN,...,True,SEC,2,2,1,2,3,3.0,NaN,-1.0
3,4,10,2021,Arizona,California,12,"Sat, Nov 6",W,False,NaN,...,True,Pac-12,122,106,71,110,122,NaN,NaN,0.0
4,5,10,2021,Arizona State,USC,9,"Sat, Nov 6",W,False,NaN,...,True,Pac-12,49,39,61,61,63,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5641,5642,9,2024,West Virginia,Arizona,277,"Sat, Oct 26",W,False,NaN,...,False,Big 12,58,63,54,64,81,NaN,NaN,0.0
5642,5643,9,2024,Western Kentucky,Kennesaw State,98,"Wed, Oct 30",W,False,NaN,...,True,CUSA,84,99,80,77,56,NaN,NaN,0.0
5643,5644,9,2024,Western Michigan,Kent State,2711,"Sat, Oct 26",W,False,NaN,...,True,MAC,103,108,70,103,87,NaN,NaN,0.0
5644,5645,9,2024,Wisconsin,Penn State,275,"Sat, Oct 26",L,False,NaN,...,True,Big Ten,55,47,32,41,76,NaN,3.0,0.0
5645,5646,9,2024,Wyoming,Utah State,2751,"Sat, Oct 26",L,False,NaN,...,True,Mountain West,119,113,97,124,125,NaN,NaN,0.0

In [6]:
teams = df['Team'].unique()
teams

array(['Air Force', 'Akron', 'Alabama', 'Arizona', 'Arizona State',
       'Arkansas', 'Army', 'Auburn', 'Ball State', 'Baylor',
       'Boise State', 'Boston College', 'Bowling Green', 'Buffalo',
       'Central Michigan', 'Charlotte', 'Cincinnati', 'Coastal Carolina',
       'Colorado', 'Colorado State', 'Duke', 'East Carolina',
       'Eastern Michigan', 'Florida', 'Florida Atlantic',
       'Florida International', 'Florida State', 'Fresno State',
       'Georgia', 'Georgia Southern', 'Georgia State', 'Georgia Tech',
       "Hawai'i", 'Houston', 'Illinois', 'Indiana', 'Iowa', 'Iowa State',
       'Kansas', 'Kansas State', 'Kent State', 'Kentucky', 'Liberty',
       'Louisiana', 'Louisiana Tech', 'Louisville', 'LSU', 'Marshall',
       'Maryland', 'Memphis', 'Miami', 'Miami (OH)', 'Michigan',
       'Michigan State', 'Middle Tennessee', 'Minnesota',
       'Mississippi State', 'Missouri', 'Navy', 'NC State', 'Nebraska',
       'New Mexico', 'North Carolina', 'North Texas', 'Northern Illinois',
       'Northwestern', 'Notre Dame', 'Ohio', 'Ohio State',
       'Oklahoma State', 'Old Dominion', 'Ole Miss', 'Oregon',
       'Oregon State', 'Penn State', 'Pittsburgh', 'Purdue', 'Rice',
       'Rutgers', 'San Diego State', 'San Jose State', 'SMU',
       'South Alabama', 'South Carolina', 'South Florida',
       'Southern Miss', 'Stanford', 'TCU', 'Temple', 'Tennessee', 'Texas',
       'Texas A&M', 'Texas State', 'Toledo', 'Troy', 'Tulane', 'Tulsa',
       'UAB', 'UCF', 'UCLA', 'UL Monroe', 'UNLV', 'USC', 'Utah',
       'Utah State', 'UTEP', 'UTSA', 'Virginia Tech', 'Wake Forest',
       'Washington', 'West Virginia', 'Western Kentucky',
       'Western Michigan', 'Wisconsin', 'Wyoming', 'BYU', 'California',
       'Clemson', 'James Madison', 'New Mexico State', 'Oklahoma',
       'Syracuse', 'Texas Tech', 'Uconn', 'Virginia', 'Washington State',
       'Arkansas State', 'Jacksonville State', 'Massachusetts', 'Nevada',
       'Vanderbilt', 'App State', 'Kennesaw State', 'Sam Houston'],
      dtype=object)

In [ ]:
team = st.selectbox('Select your team:', teams)
st.write(f'Selected team: {team{}')