**Preparing dataframe for analysis:**
-

In [10]:
import pandas as pd
import seaborn as sn

df_football = pd.read_csv('CollegeFootballRankings24to20.csv')
df_rankings = pd.read_csv('WeekByWeekRankingsUpdated.csv')
df_teams = pd.read_csv('2025 Teams.csv')
df_merge = pd.read_csv('mergedTrainingData.csv')

In [23]:
df_football.groupby(by="Team")["Team"].value_counts().sort_values()

Team
Kennesaw State Owls             13
App State Mountaineers          14
Sam Houston Bearkats            27
Jacksonville State Gamecocks    30
James Madison Dukes             42
                                ..
Texas Longhorns                 73
Army Black Knights              74
Alabama Crimson Tide            75
Notre Dame Fighting Irish       75
Georgia Bulldogs                75
Name: count, Length: 134, dtype: int64

In [25]:
df_rankings.rename(columns={"team" : "Team"}, inplace=True)
df_rankings

,Unnamed: 0.1,Unnamed: 0,AP_rank,state,week,season,code_x,state.1,code_y,Team
0,0,0,1,Georgia,1,2024,61.0,Georgia Bulldogs,NaN,NaN
1,1,1,2,Ohio State,1,2024,194.0,Ohio State Buckeyes,NaN,NaN
2,2,2,3,Oregon,1,2024,2483.0,Oregon Ducks,NaN,NaN
3,3,3,4,Texas,1,2024,251.0,Texas Longhorns,NaN,NaN
4,4,4,5,Alabama,1,2024,333.0,Alabama Crimson Tide,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1970,1970,1970,21,USC,16,2020,30.0,USC Trojans,NaN,NaN
1971,1971,1971,22,Miami,16,2020,2390.0,Miami Hurricanes,NaN,NaN
1972,1972,1972,23,Ball State,16,2020,2050.0,Ball State Cardinals,NaN,NaN
1973,1973,1973,24,San José State,16,2020,NaN,NaN,NaN,NaN
1974,1974,1974,25,Buffalo,16,2020,2084.0,Buffalo Bulls,NaN,NaN

In [13]:
df_merge.sample(40)

,Unnamed: 0,week,season,Team,opponent,code,date,win_loss,OT,OT_num,...,home_game,CONF,SOR,FPI,SOS,GC,AVGWP,AP_rank,opponent_rank,rank_change
2835,2836,3,2023,Kansas State,Missouri,2306,"Sat, Sep 16",L,False,NaN,...,False,Big 12,19,11,35,13,16,15.0,NaN,0.0
2266,2267,2,2021,Iowa,Iowa State,2294,"Sat, Sep 11",W,False,NaN,...,False,Big Ten,16,32,23,33,54,12.0,10.0,-6.0
2032,2033,14,2023,Ole Miss,Penn State,145,"Sat, Dec 30",W,False,NaN,...,True,SEC,6,15,3,12,17,11.0,10.0,-1.0
3847,3848,5,2024,Marshall,Western Michigan,276,"Sat, Sep 28",W,False,NaN,...,True,Sun Belt,34,58,64,40,21,NaN,NaN,0.0
2808,2809,3,2023,Buffalo,Liberty,2084,"Sat, Sep 16",L,False,NaN,...,True,MAC,129,115,123,122,120,NaN,NaN,0.0
820,821,11,2023,Western Kentucky,Sam Houston,98,"Sat, Nov 18",W,False,NaN,...,True,CUSA,72,89,80,84,48,NaN,NaN,0.0
3223,3224,4,2022,Wake Forest,Clemson,154,"Sat, Sep 24",L,True,2,...,True,ACC,35,32,58,26,28,16.0,5.0,-2.0
2357,2358,2,2022,Kent State,Oklahoma,2309,"Sat, Sep 10",L,False,NaN,...,False,MAC,99,97,48,100,95,NaN,7.0,0.0
4655,4656,7,2024,Akron,Western Michigan,2006,"Sat, Oct 12",L,False,NaN,...,False,MAC,111,124,55,110,110,NaN,NaN,0.0
3302,3303,4,2023,Oklahoma State,Iowa State,197,"Sat, Sep 23",L,False,NaN,...,False,Big 12,17,39,26,51,80,NaN,NaN,0.0
3246,3247,4,2023,Central Michigan,South Alabama,2117,"Sat, Sep 23",W,False,NaN,...,False,MAC,104,114,90,118,113,NaN,NaN,0.0
562,563,11,2021,Tulsa,Temple,202,"Sat, Nov 20",W,False,NaN,...,True,American,66,76,33,67,69,NaN,NaN,0.0
4608,4609,7,2023,Oklahoma State,West Virginia,197,"Sat, Oct 21",W,False,NaN,...,False,Big 12,17,39,26,51,80,NaN,NaN,0.0
1428,1429,13,2021,Eastern Michigan,Liberty,2199,"Sat, Dec 18",L,False,NaN,...,True,MAC,85,95,103,105,87,NaN,NaN,0.0
1099,1100,12,2022,Maryland,Ohio State,120,"Sat, Nov 19",L,False,NaN,...,True,Big Ten,30,31,18,42,59,NaN,2.0,0.0
4142,4143,6,2023,Boston College,Army,103,"Sat, Oct 7",W,False,NaN,...,False,ACC,61,81,76,96,100,NaN,NaN,0.0
2140,2141,14,2024,Utah State,Colorado State,328,"Fri, Nov 29",L,False,NaN,...,False,Mountain West,112,110,93,102,99,NaN,NaN,0.0
4467,4468,7,2022,Georgia Southern,James Madison,290,"Sat, Oct 15",W,False,NaN,...,True,Sun Belt,97,91,118,109,90,NaN,NaN,0.0
3875,3876,5,2024,Purdue,Nebraska,2509,"Sat, Sep 28",L,False,NaN,...,True,Big Ten,116,120,11,112,133,NaN,NaN,0.0
2001,2002,14,2023,Boise State,UNLV,68,"Sat, Dec 2",W,False,NaN,...,False,Mountain West,68,47,82,46,33,NaN,NaN,0.0
5324,5325,9,2022,Boise State,Colorado State,68,"Sat, Oct 29",W,False,NaN,...,True,Mountain West,54,54,102,65,33,NaN,NaN,0.0
1126,1127,12,2022,Pittsburgh,Duke,221,"Sat, Nov 19",W,False,NaN,...,True,ACC,24,30,62,22,20,NaN,NaN,0.0
236,237,10,2023,Akron,Miami (OH),2006,"Wed, Nov 8",L,False,NaN,...,False,MAC,132,131,127,122,119,NaN,NaN,0.0
3268,3269,4,2023,James Madison,Utah State,256,"Sat, Sep 23",W,False,NaN,...,False,Sun Belt,26,44,116,35,11,NaN,NaN,0.0
1342,1343,12,2024,Massachusetts,Liberty,113,"Sat, Nov 16",L,True,,...,True,FBS Indep.,131,125,84,119,115,NaN,NaN,0.0
4288,4289,6,2024,New Mexico,New Mexico State,167,"Sat, Sep 28",W,False,NaN,...,False,Mountain West,109,107,123,122,106,NaN,NaN,0.0
3967,3968,6,2021,North Texas,Missouri,249,"Sat, Oct 9",L,False,NaN,...,False,CUSA,101,96,126,116,93,NaN,NaN,0.0
2795,2796,3,2022,Washington,Michigan State,264,"Sat, Sep 17",W,False,NaN,...,True,Pac-12,9,20,60,14,9,NaN,9.0,0.0
2341,2342,2,2022,East Carolina,Old Dominion,151,"Sat, Sep 10",W,False,NaN,...,True,American,62,64,88,68,57,NaN,NaN,0.0
4983,4984,8,2023,Auburn,Ole Miss,2,"Sat, Oct 21",L,False,NaN,...,True,SEC,50,34,11,38,64,NaN,12.0,0.0
4988,4989,8,2023,Buffalo,Kent State,2084,"Sat, Oct 21",W,False,NaN,...,False,MAC,129,115,123,122,120,NaN,NaN,0.0
3212,3213,4,2022,UCF,Georgia Tech,2116,"Sat, Sep 24",W,False,NaN,...,True,American,45,37,72,49,44,NaN,NaN,0.0
1189,1190,12,2023,Coastal Carolina,James Madison,324,"Sat, Nov 25",L,False,NaN,...,True,Sun Belt,70,76,112,89,65,NaN,18.0,0.0
1760,1761,13,2024,Coastal Carolina,Georgia Southern,324,"Sat, Nov 23",L,False,NaN,...,True,Sun Belt,105,100,122,109,86,NaN,NaN,0.0
1138,1139,12,2022,Syracuse,Wake Forest,183,"Sat, Nov 19",L,False,NaN,...,False,ACC,50,47,49,57,70,NaN,NaN,0.0
4682,4683,7,2024,Georgia Southern,Marshall,290,"Sat, Oct 12",W,False,NaN,...,True,Sun Belt,56,78,79,87,80,NaN,NaN,0.0
3761,3762,5,2023,Old Dominion,Marshall,295,"Sat, Sep 30",L,False,NaN,...,False,Sun Belt,94,104,106,98,81,NaN,NaN,0.0
5358,5359,9,2022,Miami,Virginia,2390,"Sat, Oct 29",W,True,4,...,False,ACC,79,69,67,90,99,NaN,NaN,0.0
2180,2181,15,2024,Clemson,SMU,228,"Sat, Dec 7",W,False,NaN,...,True,ACC,25,14,28,10,10,18.0,8.0,6.0
1957,1958,14,2022,Nebraska,Iowa,158,"Fri, Nov 25",W,False,NaN,...,False,Big Ten,91,70,55,71,85,NaN,NaN,0.0

In [9]:
# Update Week Dataframe
df_rankings_cleaned = pd.merge(df_rankings, df_teams, how="left", on="Team")
print(f"There are {df_rankings_cleaned['team_and_mascot'].isnull().sum()} errors")
df_rankings_cleaned = df_rankings_cleaned.rename(columns={"year": "season", "Team":"state","Week" : "week","team_and_mascot" : "team"}) # Renamed
df_football = df_football.rename(columns={"Team" : "team"})
df_rankings_cleaned.to_csv("WeekbyWeekRankingsUpdated.csv")

There are 1975 errors

In [ ]:
# Merge the final Dataframe
df_analyze = pd.merge(df_football, df_rankings_cleaned, how = "left", on=["team","season","week"])
df_analyze.to_csv("Cleaned_Dataset.csv")

In [2]:
df_analyze

,team,date,Team_id,opponent,win_loss,OT,OT_num,pass,rush,rec,...,CONF,SOR,FPI,AP/CFP,SOS,GC,AVGWP,AP_rank,state,code
0,Air Force Falcons,"Sat, Nov 16",2005,Oregon State,W,False,NaN,110.0,97.0,68.0,...,Mountain West,108,106,--,117,115,100,NaN,NaN,NaN
1,Air Force Falcons,"Sat, Aug 31",2005,Merrimack,W,False,NaN,71.0,63.0,21.0,...,Mountain West,108,106,--,117,115,100,NaN,NaN,NaN
2,Air Force Falcons,"Sat, Sep 7",2005,San José State,L,False,NaN,54.0,50.0,36.0,...,Mountain West,108,106,--,117,115,100,NaN,NaN,NaN
3,Air Force Falcons,"Sat, Sep 14",2005,Baylor,L,False,NaN,18.0,71.0,18.0,...,Mountain West,108,106,--,117,115,100,NaN,NaN,NaN
4,Air Force Falcons,"Sat, Sep 21",2005,Bye,Bye,False,NaN,0.0,0.0,0.0,...,Mountain West,108,106,--,117,115,100,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8543,Wyoming Cowboys,"Fri, Nov 27",2751,UNLV,W,False,NaN,99.0,164.0,42.0,...,Mountain West,100,73,--,117,95,74,NaN,NaN,NaN
8544,Wyoming Cowboys,"Fri, Oct 30",2751,Hawai'i,W,False,NaN,112.0,163.0,32.0,...,Mountain West,100,73,--,117,95,74,NaN,NaN,NaN
8545,Wyoming Cowboys,"Sat, Dec 5",2751,New Mexico,L,False,NaN,73.0,154.0,54.0,...,Mountain West,100,73,--,117,95,74,NaN,NaN,NaN
8546,Wyoming Cowboys,"Thu, Nov 19",2751,Bye,Bye,False,NaN,0.0,0.0,0.0,...,Mountain West,100,73,--,117,95,74,NaN,NaN,NaN
8547,Wyoming Cowboys,"Sat, Dec 12",2751,Boise State,L,False,NaN,45.0,59.0,29.0,...,Mountain West,100,73,--,117,95,74,NaN,NaN,NaN